# Generated by Django 6.0.3 on 2026-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('event_type', models.CharField(choices=[('recipe_moderation', 'Recipe moderation'), ('review_moderation', 'Review moderation'), ('plan_moderation', 'Meal plan moderation'), ('new_complaint', 'New complaint'), ('complaint_response', 'Complaint response'), ('system', 'System')], default='system', max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
