# Generated by Django 6.0.3 on 2026-04-03 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredientchangenotice',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_change_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredientchangenotice',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_change_notices', to='recipes.recipe'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['target_type', 'target_id'], name='moderation__target__f2df77_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['decision'], name='moderation__decisio_51fa77_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['created_at'], name='moderation__created_61b135_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredientchangenotice',
            index=models.Index(fields=['recipe'], name='moderation__recipe__251ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredientchangenotice',
            index=models.Index(fields=['author_notified'], name='moderation__author__cc696b_idx'),
        ),
    ]
