# Generated by Django 6.0.3 on 2026-04-03 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_plans', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal_plans.mealplan'),
        ),
        migrations.AddField(
            model_name='mealplanitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_items', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal_plans.shoppinglist'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user'], name='meal_plans__user_id_c568ec_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['status'], name='meal_plans__status_e0a562_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['start_date', 'end_date'], name='meal_plans__start_d_84c164_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanitem',
            index=models.Index(fields=['meal_plan', 'day_number'], name='meal_plans__meal_pl_5375eb_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplanitem',
            index=models.Index(fields=['meal_type'], name='meal_plans__meal_ty_76cc6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplanitem',
            constraint=models.UniqueConstraint(fields=('meal_plan', 'day_number', 'meal_type', 'recipe'), name='unique_meal_plan_item_slot'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user'], name='meal_plans__user_id_f1c4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['status'], name='meal_plans__status_139f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list'], name='meal_plans__shoppin_b9d842_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['is_purchased'], name='meal_plans__is_purc_a5152a_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.UniqueConstraint(fields=('shopping_list', 'ingredient', 'unit'), name='unique_shopping_list_item'),
        ),
    ]
